name: HACS Validate

on:
  push:
    paths:
      - "custom_components/suncloud_monitor/**"
  pull_request:

jobs:
  validate:
    name: Validate with HACS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run HACS Validation
        uses: hacs/action@main
        with:
          category: integration
